# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: test

  logdir: logs/m40/d5
  ckpt: logs/m40/d5_05121714/best_model.pth

DATA:
  test:
    # octree building
    depth: 5
    full_depth: 2

    # transformation
    orient_normal: xyz

    # data augmentations
    distort: False
    angle: (0, 0, 5)      # small rotation along z axis
    interval: (1, 1, 1)
    scale: 0.25
    jitter: 0.125

    # data loading
    location: data/ModelNet40/ModelNet40.ply.normalize
    filelist: data/ModelNet40/filelist/m40_test.txt
    batch_size: 32
    shuffle: False
    # num_workers: 0

MODEL:
  name: lenet
  feature: ND   # N -> Normal (3 channels);
                # D -> Local displacement (1 channel)
  nempty: False
  stages: 3     # !!! `stages` should increase with `depth` accordingly
  channel: 4
  nout: 40

LOSS:
  num_class: 40
