# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train
  best_val: min:loss
  port: 10001         # the port used for multi-gpu training

  logdir: logs/image2shape/image2shape
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 20

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  milestones: (160,240) # not used for `poly`

DATA:
  train:
    name: image2shape

    # octree building
    depth: 6
    full_depth: 2
    points_scale: 0.5

    # no data augmentations
    distort: False

    # data loading
    location: data/ShapeNetV1/points.npz
    filelist: data/ShapeNetV1/filelist/train.txt
    filetype: npz  # file type of the point clouds
    batch_size: 32
    shuffle: True
    # num_workers: 0

  test:
    name: image2shape

    # octree building
    depth: 6
    full_depth: 2
    points_scale: 0.5

    # no data augmentations
    distort: False

    # data loading
    location: data/ShapeNetV1/points.npz
    filelist: data/ShapeNetV1/filelist/test.txt
    filetype: npz # file type of the point clouds
    batch_size: 16
    shuffle: False
    # num_workers: 0

MODEL:
  name: image2shape
  depth: 6
  full_depth: 2
  channel_out: 4
